[project]
name = "partscape"
authors = [
    { name = "Seityl Group Ltd.", email = "contact@seityl.com" }
]
description = "Auto-parts intelligence system for auto parts stores"
requires-python = ">=3.10"
readme = "README.md"
license = {text = "Proprietary"}
dynamic = ["version"]
dependencies = [
    "requests>=2.28.0",
    "rapidfuzz>=3.0.0",
    "brother-ql>=0.9",
    "python-barcode>=0.13.1",
    "Pillow>=9.0.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
